name: Docker CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker image
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-cicd-demo:latest .

      # 4. Push image to registry
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-cicd-demo:latest